#!/usr/bin/env bash
set -euo pipefail

repo_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
registry="https://npm.pkg.github.com"
if ! token="$(gh auth token)"; then
  echo "Error: Failed to get GitHub token. Please ensure you are logged in with 'gh auth login'." >&2
  exit 1
fi

cat > "${repo_dir}/.npmrc" <<EOF
@Blue-Water-Autonomy:registry=${registry}
//npm.pkg.github.com/:_authToken=${token}
EOF

echo '.npmrc written for GitHub Packages.'

cd "${repo_dir}"
yarn lerna publish \
  --no-private \
  --ignore "@blue-water-autonomy/html-eslint-cli" \
  --preid 'bwa' \
  --registry="${registry}" prerelease
